name: Format Nautilus
run-name: ${{ github.actor }} checks format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# cancel previous runs of same PR / branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    runs-on: ubuntu-24.04
    name: Check format
    steps:
      - uses: actions/checkout@v4
      - name: run format.sh
        run: |
          ./format.sh
